### ISSUE TITLE
executable of calculator.nim does not do anything

### ISSUE THREAD

**Issue by apahl** [redacted-moose/nuklear.nim#1]
Woohoo, first issue !!

First of all, thanks a lot for porting this lib to Nim.
  
I cloned the repo and installed via `nimble install`.  
I managed to compile the `calculator.nim` demo with `nim c calculator.nim` (I had to change the `passC: "-Inuklear/"` in `wrapper.nim` to the absolute path) and I get an executable, but it doesn't do anything.  
The program starts and directly quits again, without any messages.

This is on Ubuntu 16.10 with Nim devel.

Do you have any idea what could be wrong?

Many thanks in advance for your help.

Kind regards,  
Axel

**Comment by redacted-moose** [comment]
Wow, someone is actually using this.  Awesome!

The reason why this does nothing is because `calculator.nim` only defines the logic for the gui, but doesn't have any code to handle window creation or anything else.

To get the calculator demo to run, what you need to do is uncomment the lines [here](https://github.com/redacted-moose/nuklear.nim/blob/master/demo/sdl_opengl2/main.nim#L25) and [here](https://github.com/redacted-moose/nuklear.nim/blob/master/demo/sdl_opengl2/main.nim#L151), as well as comment out the lines related to the node editor near these lines.  The structure is similar in the [glfw_opengl2](https://github.com/redacted-moose/nuklear.nim/blob/master/demo/glfw_opengl2/main.nim) demo as well.

You should then be able to do `nimble sdl_opengl2` (or `nimble glfw_opengl2` if you change the glfw demo) and it should build; if this doesn't work, try `nim c -r demo/glfw_opengl2/main.nim`.  If in doubt, take a look inside `nuklear.nimble` in the project root.

Be warned though: this is a pretty raw wrapper right now, and I'm pretty sure the calculator demo itself has some issues that need to be sorted out, so I wouldn't expect it to function correctly yet.  You might be better off trying to get one of the other demos working (the node editor works for instance).  This repo is layed out pretty much the same as [vurtun's](https://github.com/vurtun/nuklear) if you have any questions about the structure.

If you feel like fixing up the demos or contributing, pull requests are welcome!

**Comment by apahl** [comment]
Great, I got the sdl_opengl2 demo to run, thanks for your help. This looks really promising and seems to be very responsive.

When building GUI tools, I am mainly interested in cross-compiling to Windows, I will try that out, next.

Many thanks again,  
Axel
